spring:
  datasource:
    url: jdbc:mysql://YOUR_RDS_ENDPOINT:3306/posit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: YOUR_USERNAME
    password: YOUR_PASSWORD
    driver-class-name: com.mysql.cj.jdbc.Driver