spring:
  datasource:
    url: jdbc:mysql://localhost:3307/posit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: posit
    password: positpw
    driver-class-name: com.mysql.cj.jdbc.Driver